# Generated by Django 5.2.3 on 2025-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bengluru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mumbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
    ]
