# Generated by Django 5.2.3 on 2025-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chennai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Delhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hydrabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(choices=[('Developer', 'Developer'), ('Marketing', 'Marketing'), ('VP', 'VP'), ('CTO', 'CTO')], max_length=15)),
                ('sal', models.IntegerField()),
                ('qualification', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('bcs', 'bcs'), ('msc', 'msc')], max_length=15)),
                ('joining_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('mode', models.CharField(choices=[('WFH', 'WFH'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='bengluru',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pune',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
